# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LXvuVLEaxX+X8Ovw8x7cohPVO0sz5l8SzhBohRhbKLQifjSO+lQx/630p4NKbooNO3bpLRCslAcY3CPzf/aJ95D0LPrD/tdKTaA8jmU1sOB/XKUyAuwXDGtHvjKxnQBCdYJxfhCtdr2O7Ls0QtA5H26cKXQckAXXkzmpy67XC5QtPSj7HOKZbfEtdXNS/1mhVxgQil1FVGo6MW372kDSj2QQliFBXfdMUp5ddQ4f08sNyNfcHJB/x5Wjf1lj6gePoeB2hN2w+aR7ZwiWK+NASClC8OtE0EHqxjgDpiJ27gYkgAwikpfyA8p07QlsPpBvjFbYH6KUJdZL7t55nu8c/5fUfP1rjiFmB+rz0hz5Qq/tBa8A7GeokwPVFuaY5flJT6w6FOmVPIHjFPWpGYKW6b/goDhRlLF1M/IdcyOGP8nS0Us+xZz+56aAOlB/YTuya6g4L3uuWH7YKilmGx3cvS+mLX1VQjAyATEhvze/qP4sawOo44jQ4eDySaWrVXRQwZCDYxp98VV5MKM0HKIkXBaUqnnJZBcIPLw4IZTAFAmr0L2ZC/a1YPFuErU0EKenv1wMulOgQQa4onQC+k93HqKcyXlQ3TvNYyL7mDqI5UTh5mh23NdQD7/kfJct82JbS3IjXyfhMN4qb2xhrGtE1SpZxm0xGPjNPO+oUevCBeg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
