travis:
  secure:
    BINSTAR_TOKEN: JLkI7FtB/HxeKNmu+EM2T1UqyqtfUGOJwk/GnmBSeC/RAHKIh8W2iWsDJLwbiFYjzKCQ0k3wcrYrgPDL3EwriUkmzqxjkn3X8DdjEtzQ7TlDAJohA9kV5U6heHgkskoFbUmB3ni1mqpgLIqKkKfWWziU+2z4ngxYVy5lfXAaU08r8+kpJG+5+TPIF2GQcfacF63khwiRluYfjYQLAVlmN6SKKmpMx1Zy95+QZmN2VcWbtP5SsWYmislWZBBY2DhjCCqB2R/at03KMkREtRXoDkl70mJ+G1EU8XOaZ8iNUcaJBnC+NQM7MFZHFz/MZILeLPsSPgeNPzGh5NDfjMliGUtUlvkIqgULh2DiGr/sw8sO5DhWTagsq83Ilkq4XnY0nljXdCTjEjhPbq2LvdH6JCqzKa4Hs6tYbGq4QZsaSF0K29JOfuSftWCW3jXcOKu+XjPGMijIpLEw++0Gg28W4shAwyBPiqnEkyAoNYfwvtsdV1Bl7QTjh/6u3BWgGBXxraU7nBqKf/SRheJ3B3kbenozSR8SowDH0sACU4K957HL0uD4LiL/T38AdVv+U3TDVP39zmz9vsmtjCBM0jUOc467iHNMkep15uicDjbwttml3n0yN8db7IsFSGvlXWLHLGluN72UenIJ9r89Tg7p+BLpJmtz+pWQNlN7ryXtHPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
