appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LXvuVLEaxX+X8Ovw8x7cohPVO0sz5l8SzhBohRhbKLQifjSO+lQx/630p4NKbooNO3bpLRCslAcY3CPzf/aJ95D0LPrD/tdKTaA8jmU1sOB/XKUyAuwXDGtHvjKxnQBCdYJxfhCtdr2O7Ls0QtA5H26cKXQckAXXkzmpy67XC5QtPSj7HOKZbfEtdXNS/1mhVxgQil1FVGo6MW372kDSj2QQliFBXfdMUp5ddQ4f08sNyNfcHJB/x5Wjf1lj6gePoeB2hN2w+aR7ZwiWK+NASClC8OtE0EHqxjgDpiJ27gYkgAwikpfyA8p07QlsPpBvjFbYH6KUJdZL7t55nu8c/5fUfP1rjiFmB+rz0hz5Qq/tBa8A7GeokwPVFuaY5flJT6w6FOmVPIHjFPWpGYKW6b/goDhRlLF1M/IdcyOGP8nS0Us+xZz+56aAOlB/YTuya6g4L3uuWH7YKilmGx3cvS+mLX1VQjAyATEhvze/qP4sawOo44jQ4eDySaWrVXRQwZCDYxp98VV5MKM0HKIkXBaUqnnJZBcIPLw4IZTAFAmr0L2ZC/a1YPFuErU0EKenv1wMulOgQQa4onQC+k93HqKcyXlQ3TvNYyL7mDqI5UTh5mh23NdQD7/kfJct82JbS3IjXyfhMN4qb2xhrGtE1SpZxm0xGPjNPO+oUevCBeg=}
